# Config file for the app
#

#  SECTION:============================================================= 
#            Secrets     
#  ===================================================================== 

# ## Secret values should be written in /secrets/
# [secrets]
# gas_id = ""


#  SECTION:============================================================= 
#            Configs, Basic
#  ===================================================================== 

[endpoints]
speech_recognition = "/speech-recognition"
speech_recognition_ws = "/ws/speech-recognition"
obs_speech_overlay = "/obs-speech-overlay"
obs_speech_overlay_ws = "/ws/obs-speech-overlay"

[htmls]
speech_recognition = "speech-recognition.html"
obs_speech_overlay = "obs-speech-overlay.html"

[heartbeat]
text = "heartbeat"
interval = 20
timeout = 3

#  SECTION:============================================================= 
#            Configs, Added featrues     
#  ===================================================================== 

# logging selected values
[logging]
enable = true
filepath = "/tmp/logfile.log"
timestamp_format = "%Y-%m-%d %H:%M:%S"
final_text_enable = true
translation_enable = true

[translation]
enable = true
source_language = "ja"
target_language = "en"
# Translation API
api_type = "gas"
# gas base url pattern. Write gas_id in secrets/ like filename:gas_id content:gas id
api_base_url = "https://script.google.com/macros/s/{gas_id}/exec"
# Empty is OK. gas api url is generated from api_base_url + gas_id(which is in secrets/. If nothing. Write it.)
api_url = ""

# Voicevox
[voicevox]
enable = true

[voicevox.server]
host = "127.0.0.1"
port = 50021

[voicevox.male_voice]
speaker = 13
speed = 1.2
pitch = 1.0
intonation = 1.0
volume = 1.0

[voicevox.female_voice]
speaker = 14
speed = 1.2
pitch = 1.0
intonation = 1.0
volume = 1.0
